import type {
  Concept,
  ContentPackVersion,
  Control,
  GlossaryTerm,
  Journey,
  JurisdictionPack,
  NetworkProfile,
  Pattern,
  ReleaseNote,
  SimulationScenario,
  SourceCard,
} from './types';

export const lensOptions = [
  { id: 'learning', label: 'Learning Lens' },
  { id: 'client', label: 'Client Lens' },
  { id: 'product', label: 'Product Lens' },
  { id: 'operations', label: 'Operations Lens' },
  { id: 'risk', label: 'Risk / Legal Lens' },
  { id: 'technology', label: 'Technology Lens' },
  { id: 'executive', label: 'Executive Lens' },
] as const;

export const depthOptions = [
  { id: 'plain', label: 'Plain English' },
  { id: 'practitioner', label: 'Practitioner' },
  { id: 'expert', label: 'Expert' },
] as const;

export const clientSegments = [
  { id: 'retail', label: 'Retail' },
  { id: 'affluent', label: 'Affluent' },
  { id: 'hnw', label: 'HNW' },
  { id: 'uhnw', label: 'UHNW' },
  { id: 'family-office', label: 'Family Office' },
  { id: 'institutional', label: 'Institutional' },
  { id: 'corporate-treasury', label: 'Corporate Treasury' },
  { id: 'issuer', label: 'Issuer / Originator' },
] as const;

export const sourceCards: SourceCard[] = [
  {
    id: 'finma-guidance-01-2026',
    title: 'FINMA Guidance 01/2026 on custody of crypto-based assets',
    organization: 'FINMA',
    url: 'https://www.finma.ch/en/~/media/finma/dokumente/dokumentencenter/myfinma/4dokumentation/finma-aufsichtsmitteilungen/20260112-finma-aufsichtsmitteilung-01-2026.pdf',
    sourceType: 'guidance',
    jurisdiction: 'ch',
    status: 'final',
    lastReviewed: '2026-03-18',
    staleAfterDays: 45,
    owner: 'product-research',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['custody', 'segregation', 'delegated custody'],
    impactAreas: ['markets', 'controls', 'simulations'],
    summary: 'Primary Swiss custody guidance for crypto-based assets, including safeguarding and delegation concerns.',
  },
  {
    id: 'esma-mica',
    title: 'ESMA MiCA hub',
    organization: 'ESMA',
    url: 'https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica',
    sourceType: 'official-page',
    jurisdiction: 'eu',
    status: 'final',
    lastReviewed: '2026-03-18',
    staleAfterDays: 30,
    owner: 'product-research',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['MiCA', 'CASP', 'registers'],
    impactAreas: ['learn', 'markets', 'controls'],
    summary: 'Entry point for MiCA materials, registers, and supporting ESMA publications.',
  },
  {
    id: 'eu-dora',
    title: 'Digital Operational Resilience Act',
    organization: 'European Union',
    url: 'https://eur-lex.europa.eu/eli/reg/2022/2554/oj',
    sourceType: 'law',
    jurisdiction: 'eu',
    status: 'final',
    lastReviewed: '2026-03-18',
    staleAfterDays: 90,
    owner: 'risk-governance',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['operational resilience', 'ICT risk', 'incident management'],
    impactAreas: ['controls', 'simulations'],
    summary: 'EU operational resilience regulation that materially shapes incident, outsourcing, and resilience expectations.',
  },
  {
    id: 'boe-dss',
    title: 'Bank of England Digital Securities Sandbox',
    organization: 'Bank of England',
    url: 'https://www.bankofengland.co.uk/financial-stability/digital-securities-sandbox',
    sourceType: 'official-page',
    jurisdiction: 'uk',
    status: 'sandbox',
    lastReviewed: '2026-03-18',
    staleAfterDays: 45,
    owner: 'product-research',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['DSS', 'digital securities', 'sandbox'],
    impactAreas: ['markets', 'simulations'],
    summary: 'Official description of the UK Digital Securities Sandbox and its permitted scope.',
  },
  {
    id: 'fca-future-crypto',
    title: 'FCA new regime for cryptoasset regulation',
    organization: 'FCA',
    url: 'https://www.fca.org.uk/firms/new-regime-cryptoasset-regulation',
    sourceType: 'official-page',
    jurisdiction: 'uk',
    status: 'statement',
    lastReviewed: '2026-03-18',
    staleAfterDays: 45,
    owner: 'product-research',
    confidence: 'medium',
    criticality: 'high',
    relevanceTags: ['future regime', 'uk', 'cryptoassets'],
    impactAreas: ['markets', 'controls'],
    summary: 'UK forward-looking regime material that signals where legal review is required before launch assumptions are made.',
  },
  {
    id: 'mas-project-guardian',
    title: 'Project Guardian',
    organization: 'Monetary Authority of Singapore',
    url: 'https://www.mas.gov.sg/schemes-and-initiatives/project-guardian',
    sourceType: 'official-page',
    jurisdiction: 'sg',
    status: 'statement',
    lastReviewed: '2026-03-18',
    staleAfterDays: 45,
    owner: 'product-research',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['tokenized funds', 'institutional DeFi', 'commercialisation'],
    impactAreas: ['learn', 'markets', 'simulations'],
    summary: 'Singapore’s main official hub for tokenisation workstreams and institutional use-case references.',
  },
  {
    id: 'mas-stablecoin',
    title: 'MAS finalises stablecoin regulatory framework',
    organization: 'Monetary Authority of Singapore',
    url: 'https://www.mas.gov.sg/news/media-releases/2023/mas-finalises-stablecoin-regulatory-framework',
    sourceType: 'official-press-release',
    jurisdiction: 'sg',
    status: 'final',
    lastReviewed: '2026-03-18',
    staleAfterDays: 60,
    owner: 'product-research',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['stablecoin', 'reserve assets', 'redemption'],
    impactAreas: ['markets', 'controls', 'simulations'],
    summary: 'Official statement of Singapore’s stablecoin framework and core expectations.',
  },
  {
    id: 'sfc-aspire',
    title: 'SFC ASPIRe roadmap',
    organization: 'SFC',
    url: 'https://www.sfc.hk/en/News-and-announcements/Policy-statements-and-announcements/A-S-P-I-Re-for-a-brighter-future-SFCs-regulatory-roadmap-for-Hong-Kongs-virtual-asset-market',
    sourceType: 'official-page',
    jurisdiction: 'hk',
    status: 'statement',
    lastReviewed: '2026-03-18',
    staleAfterDays: 45,
    owner: 'product-research',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['Hong Kong', 'virtual assets', 'roadmap'],
    impactAreas: ['markets'],
    summary: 'Hong Kong roadmap source used for market posture and confidence framing.',
  },
  {
    id: 'hkma-stablecoin',
    title: 'HKMA stablecoin issuers regime',
    organization: 'Hong Kong Monetary Authority',
    url: 'https://www.hkma.gov.hk/eng/key-functions/international-financial-centre/stablecoin-issuers/',
    sourceType: 'official-page',
    jurisdiction: 'hk',
    status: 'final',
    lastReviewed: '2026-03-18',
    staleAfterDays: 45,
    owner: 'product-research',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['stablecoin', 'licensing'],
    impactAreas: ['markets', 'controls'],
    summary: 'Official stablecoin issuer regime material for Hong Kong.',
  },
  {
    id: 'sec-crypto-2026',
    title: 'SEC application of federal securities laws to crypto assets',
    organization: 'SEC',
    url: 'https://www.sec.gov/newsroom/press-releases/2026-30-sec-clarifies-application-federal-securities-laws-crypto-assets',
    sourceType: 'official-press-release',
    jurisdiction: 'us',
    status: 'statement',
    lastReviewed: '2026-03-18',
    staleAfterDays: 30,
    owner: 'legal-review',
    confidence: 'medium',
    criticality: 'high',
    relevanceTags: ['US', 'securities laws', 'cryptoassets'],
    impactAreas: ['markets', 'controls'],
    summary: 'Useful directional source, but US launch decisions still require specialist legal review.',
  },
  {
    id: 'adgm-frt',
    title: 'ADGM fiat-referenced token framework',
    organization: 'ADGM',
    url: 'https://www.adgm.com/media/announcements/adgm-fsra-finalises-regulatory-framework-for-regulated-activities-involving-fiat-referenced-tokens',
    sourceType: 'official-page',
    jurisdiction: 'adgm',
    status: 'final',
    lastReviewed: '2026-03-18',
    staleAfterDays: 60,
    owner: 'product-research',
    confidence: 'high',
    criticality: 'medium',
    relevanceTags: ['ADGM', 'fiat-referenced tokens'],
    impactAreas: ['markets'],
    summary: 'Regional reference point for regulated activities involving fiat-referenced tokens.',
  },
  {
    id: 'japan-fsa-2025',
    title: 'FSA paper on regulatory systems related to cryptoassets',
    organization: 'Financial Services Agency Japan',
    url: 'https://www.fsa.go.jp/en/news/2025/20250410_2/01.pdf',
    sourceType: 'guidance',
    jurisdiction: 'jp',
    status: 'statement',
    lastReviewed: '2026-03-18',
    staleAfterDays: 60,
    owner: 'product-research',
    confidence: 'medium',
    criticality: 'medium',
    relevanceTags: ['Japan', 'regulatory systems'],
    impactAreas: ['markets'],
    summary: 'High-level Japanese framework source for cautious summary coverage.',
  },
  {
    id: 'basel-crypto',
    title: 'Basel prudential treatment of cryptoasset exposures',
    organization: 'Basel Committee',
    url: 'https://www.bis.org/bcbs/publ/d545.pdf',
    sourceType: 'standard',
    jurisdiction: 'global',
    status: 'final',
    lastReviewed: '2026-03-18',
    staleAfterDays: 120,
    owner: 'risk-governance',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['prudential treatment', 'capital', 'risk'],
    impactAreas: ['controls', 'simulations'],
    summary: 'Global prudential anchor for exposure, capital, and risk framing.',
  },
  {
    id: 'nist-csf-2',
    title: 'NIST Cybersecurity Framework 2.0',
    organization: 'NIST',
    url: 'https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf',
    sourceType: 'standard',
    jurisdiction: 'global',
    status: 'final',
    lastReviewed: '2026-03-18',
    staleAfterDays: 180,
    owner: 'cyber-risk',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['cyber', 'governance', 'resilience'],
    impactAreas: ['controls', 'simulations'],
    summary: 'Cross-cutting cyber and resilience anchor for the control library.',
  },
  {
    id: 'fatf-vasp-2025',
    title: 'FATF targeted update on virtual assets and VASPs',
    organization: 'FATF',
    url: 'https://www.fatf-gafi.org/en/publications/Fatfrecommendations/targeted-update-virtual-assets-vasps-2025.html',
    sourceType: 'standard',
    jurisdiction: 'global',
    status: 'final',
    lastReviewed: '2026-03-18',
    staleAfterDays: 120,
    owner: 'fcc-controls',
    confidence: 'high',
    criticality: 'high',
    relevanceTags: ['travel rule', 'AML', 'VASP'],
    impactAreas: ['controls', 'simulations'],
    summary: 'Global AML and Travel Rule anchor for transfer and screening controls.',
  },
  {
    id: 'ubs-tokenize',
    title: 'UBS Tokenize',
    organization: 'UBS',
    url: 'https://www.ubs.com/global/en/investment-bank/tokenize.html',
    sourceType: 'official-page',
    jurisdiction: 'global',
    status: 'press-release',
    lastReviewed: '2026-03-18',
    staleAfterDays: 60,
    owner: 'market-research',
    confidence: 'medium',
    criticality: 'medium',
    relevanceTags: ['tokenized bonds', 'funds', 'structured products'],
    impactAreas: ['learn', 'networks', 'patterns'],
    summary: 'Market exemplar for bank-led tokenisation patterns without implying endorsement.',
  },
  {
    id: 'chainlink-dta',
    title: 'Chainlink DTA technical standard',
    organization: 'Chainlink',
    url: 'https://chain.link/digital-transfer-agent-technical-standard',
    sourceType: 'official-page',
    jurisdiction: 'global',
    status: 'press-release',
    lastReviewed: '2026-03-18',
    staleAfterDays: 60,
    owner: 'market-research',
    confidence: 'medium',
    criticality: 'medium',
    relevanceTags: ['digital transfer agent', 'tokenized funds'],
    impactAreas: ['patterns', 'simulations', 'networks'],
    summary: 'Vendor-origin technical material that helps explain tokenized fund synchronization patterns.',
  },
  {
    id: 'kinexys-digital-payments',
    title: 'Kinexys Digital Payments',
    organization: 'J.P. Morgan',
    url: 'https://www.jpmorgan.com/kinexys/digital-payments',
    sourceType: 'official-page',
    jurisdiction: 'global',
    status: 'press-release',
    lastReviewed: '2026-03-18',
    staleAfterDays: 60,
    owner: 'market-research',
    confidence: 'medium',
    criticality: 'medium',
    relevanceTags: ['digital payments', 'bank rail'],
    impactAreas: ['networks', 'patterns'],
    summary: 'Bank-run settlement rail reference point for treasury and payments comparisons.',
  },
  {
    id: 'sdx-official',
    title: 'SDX official site',
    organization: 'SIX Digital Exchange',
    url: 'https://www.sdx.com/',
    sourceType: 'official-page',
    jurisdiction: 'ch',
    status: 'press-release',
    lastReviewed: '2026-03-18',
    staleAfterDays: 60,
    owner: 'market-research',
    confidence: 'medium',
    criticality: 'medium',
    relevanceTags: ['regulated DLT venue', 'settlement'],
    impactAreas: ['networks', 'simulations'],
    summary: 'Primary market reference for a regulated DLT venue and settlement environment.',
  },
  {
    id: 'digift-official',
    title: 'DigiFT official site',
    organization: 'DigiFT',
    url: 'https://www.digift.io/',
    sourceType: 'official-page',
    jurisdiction: 'sg',
    status: 'press-release',
    lastReviewed: '2026-03-18',
    staleAfterDays: 60,
    owner: 'market-research',
    confidence: 'medium',
    criticality: 'medium',
    relevanceTags: ['venue', 'tokenized funds'],
    impactAreas: ['networks', 'patterns'],
    summary: 'Reference venue pattern for tokenized funds and institutional access.',
  },
];

export const glossaryTerms: GlossaryTerm[] = [
  { id: 'dvp', term: 'Delivery versus Payment (DvP)', shortDefinition: 'A settlement pattern that exchanges asset and cash together.', practitionerNote: 'Used to reduce principal risk in issuance, trading, and repo workflows.', expertNote: 'The key question is whether the implementation is atomic, conditional, or only operationally coordinated.', relatedTerms: ['pvp', 'finality'], sourceIds: ['sdx-official'] },
  { id: 'pvp', term: 'Payment versus Payment (PvP)', shortDefinition: 'A settlement pattern exchanging one payment leg for another.', practitionerNote: 'Relevant to FX and cross-border tokenized cash flows.', expertNote: 'PvP design must specify finality timing, prefunding, and failure handling per leg.', relatedTerms: ['dvp', 'finality'], sourceIds: ['kinexys-digital-payments'] },
  { id: 'finality', term: 'Finality', shortDefinition: 'The point at which a transfer is treated as irreversible for operational purposes.', practitionerNote: 'Different rails and venues define confirmation and reversal risk differently.', expertNote: 'Risk systems must map finality assumptions to collateral, treasury, and failover logic.', relatedTerms: ['dvp', 'reconciliation'], sourceIds: ['boe-dss'] },
  { id: 'travel-rule', term: 'Travel Rule', shortDefinition: 'Information-sharing expectations for certain virtual asset transfers.', practitionerNote: 'Transfer workflows need screening and data-handling checkpoints.', expertNote: 'Scope, thresholds, and counterparty obligations vary, so deterministic control gates matter.', relatedTerms: ['aml', 'screening'], sourceIds: ['fatf-vasp-2025'] },
  { id: 'stablecoin', term: 'Stablecoin', shortDefinition: 'A token designed to reference a fiat currency or another value source.', practitionerNote: 'Not all stablecoins have the same redemption, reserve, or perimeter characteristics.', expertNote: 'Legal claim structure, reserve governance, bankruptcy treatment, and licensing perimeter matter more than the label.', relatedTerms: ['tokenized-deposit', 'emt'], sourceIds: ['mas-stablecoin', 'hkma-stablecoin'] },
  { id: 'tokenized-deposit', term: 'Tokenized Deposit', shortDefinition: 'A tokenized representation of a bank deposit or commercial-bank-money claim.', practitionerNote: 'Used as a comparison point against stablecoins for treasury and DvP workflows.', expertNote: 'The core questions are legal claim, transferability, operating perimeter, and settlement finality.', relatedTerms: ['stablecoin', 'bank-rail'], sourceIds: ['kinexys-digital-payments'] },
  { id: 'emt', term: 'E-money Token (EMT)', shortDefinition: 'A MiCA-defined token referencing a single official currency.', practitionerNote: 'Relevant in EU stablecoin perimeter analysis.', expertNote: 'Product design must consider issuer obligations, redemption, disclosures, and service-provider roles.', relatedTerms: ['stablecoin'], sourceIds: ['esma-mica'] },
  { id: 'casp', term: 'Crypto-Asset Service Provider (CASP)', shortDefinition: 'A regulated role under MiCA for certain crypto-asset services.', practitionerNote: 'Useful shorthand for service perimeter in EU scenarios.', expertNote: 'Role splitting matters because custody, trading, and transfer services can carry different evidence and resilience burdens.', relatedTerms: ['mica'], sourceIds: ['esma-mica'] },
  { id: 'frt', term: 'Fiat-Referenced Token (FRT)', shortDefinition: 'A token referencing one or more fiat currencies.', practitionerNote: 'Used in some regulatory regimes to differentiate tokenized cash designs.', expertNote: 'Perimeter and reserve requirements can differ from other tokenized money forms.', relatedTerms: ['stablecoin'], sourceIds: ['adgm-frt'] },
  { id: 'whitelisting', term: 'Wallet Whitelisting', shortDefinition: 'A process that limits transfers to approved wallets or identities.', practitionerNote: 'Common in tokenized funds, securities, and controlled distribution models.', expertNote: 'The control design must specify identity binding, exception handling, and evidence retention.', relatedTerms: ['transfer-restriction'], sourceIds: ['chainlink-dta'] },
  { id: 'nav', term: 'Net Asset Value (NAV)', shortDefinition: 'A per-unit valuation measure used by funds.', practitionerNote: 'Tokenized fund flows depend on price timing and source governance.', expertNote: 'Stale or disputed NAV can invalidate mint, burn, fee, and reporting flows.', relatedTerms: ['reconciliation'], sourceIds: ['mas-project-guardian'] },
  { id: 'segregation', term: 'Segregation', shortDefinition: 'Operational and legal separation of client assets from firm assets.', practitionerNote: 'Central to custody credibility.', expertNote: 'Segregation analysis must consider omnibus structures, delegation, insolvency treatment, and evidence models.', relatedTerms: ['custody'], sourceIds: ['finma-guidance-01-2026'] },
  { id: 'reconciliation', term: 'Reconciliation', shortDefinition: 'The process of matching records across systems.', practitionerNote: 'Tokenized products often need on-chain and off-chain record alignment.', expertNote: 'Source-of-truth design must define acceptable mismatch tolerance, escalation, and remediation timeframes.', relatedTerms: ['finality', 'nav'], sourceIds: ['chainlink-dta'] },
  { id: 'dora', term: 'DORA', shortDefinition: 'EU Digital Operational Resilience Act.', practitionerNote: 'A major operational resilience overlay for EU-facing services.', expertNote: 'The consequences are broad: incident processes, outsourcing governance, testing, and ICT controls.', relatedTerms: ['incident-response'], sourceIds: ['eu-dora'] },
  { id: 'prudential', term: 'Prudential Treatment', shortDefinition: 'How exposures are treated for capital and risk purposes.', practitionerNote: 'Important for treasury, large-value safekeeping, and institutional product design.', expertNote: 'Even illustrative scenarios should show when prudential burden can change economic viability.', relatedTerms: ['capital'], sourceIds: ['basel-crypto'] },
  { id: 'cold-storage', term: 'Cold Storage', shortDefinition: 'A custody model that keeps signing material offline.', practitionerNote: 'Often used for large-value or low-velocity holdings.', expertNote: 'Operational latency, recovery, delegation, and approval design still need explicit treatment.', relatedTerms: ['custody'], sourceIds: ['finma-guidance-01-2026'] },
];

export const concepts: Concept[] = [
  {
    id: 'native-crypto-exposure',
    title: 'Native crypto exposure',
    summary: 'How direct crypto holdings differ from wrappers such as funds, ETPs, or structured notes.',
    plain: 'Direct crypto means the client or institution is exposed to the underlying asset itself, not a wrapper around it.',
    practitioner: 'The operational questions start immediately: how onboarding works, who controls custody, how transfers are screened, and how statements and valuation are handled.',
    expert: 'Serious design work needs legal perimeter analysis, custody segregation evidence, travel-rule relevance, valuation source governance, and incident handling design.',
    whyItMatters: ['Clients often ask for “crypto” when they really mean one of several different wrappers.', 'The control burden changes sharply depending on whether transferability is enabled.'],
    misconceptions: ['Direct crypto exposure is not the same as a tokenized fund.', 'Institutional-grade custody is not solved by saying “cold wallet”.'],
    clientImpacts: {
      retail: 'Suitability, disclosure, and product simplicity dominate.',
      affluent: 'Operating model and reporting quality become more visible.',
      hnw: 'Transfer control and advisor explanation matter.',
      uhnw: 'Governance, succession, and recovery concerns become material.',
      'family-office': 'Wrapper selection, delegation, and evidencing are central.',
      institutional: 'Liquidity, accounting, and resilience become dominant.',
      'corporate-treasury': 'Usually unsuitable except in narrowly framed cases.',
      issuer: 'Mostly relevant as a benchmark rather than the target state.',
    },
    jurisdictionNotes: {
      ch: 'Swiss custody guidance provides a useful anchor for safeguarding analysis.',
      eu: 'MiCA framing and service roles drive perimeter thinking.',
      uk: 'Distinguish digital securities from unbacked crypto clearly.',
      sg: 'Institutional use cases dominate the official narrative.',
      hk: 'Product and platform permissions remain important.',
      us: 'Treat all launch assumptions as high-review items.',
    },
    relatedGlossary: ['travel-rule', 'segregation', 'cold-storage'],
    relatedPatterns: ['delegated-custody-model'],
    relatedSimulations: ['native-crypto-lifecycle'],
    relatedControls: ['ctl-suitability', 'ctl-custody-segregation', 'ctl-travel-rule'],
    sourceIds: ['finma-guidance-01-2026', 'fatf-vasp-2025', 'sec-crypto-2026'],
    lastReviewed: '2026-03-18',
    reviewOwner: 'product-research',
    freshnessDays: 45,
  },
  {
    id: 'tokenized-funds',
    title: 'Tokenized funds',
    summary: 'Fund units represented through tokenized issuance, transfer, and servicing mechanics.',
    plain: 'A tokenized fund still needs fund documents, investor checks, pricing, and servicing.',
    practitioner: 'Tokenization changes distribution, wallet controls, transfer restrictions, and record synchronization, but not the need for investor-eligibility and servicing processes.',
    expert: 'The hardest design choices usually concern transfer-agent architecture, wallet identity binding, NAV governance, and on-chain versus off-chain source-of-truth policy.',
    whyItMatters: ['Tokenized funds are one of the clearest institutional tokenization patterns with real operational depth.', 'They are a good test case for controlled transferability and synchronised records.'],
    misconceptions: ['A tokenized fund is not just “a token on a chain”.', 'Putting units on-chain does not remove transfer restrictions or NAV dependencies.'],
    clientImpacts: {
      retail: 'Most flows remain highly controlled or inappropriate for broad retail distribution.',
      affluent: 'The explanation must stay client-ready and avoid implying liquidity that does not exist.',
      hnw: 'Operational clarity on custody and transfer restrictions is critical.',
      uhnw: 'Family governance and wrapper selection matter when holding structure is complex.',
      'family-office': 'Reporting, delegation, and control over wallet authority are important.',
      institutional: 'Wallet whitelisting, reconciliation, and cut-off discipline are central.',
      'corporate-treasury': 'Generally relevant only for treasury-managed liquidity investments.',
      issuer: 'A key pattern for distribution and servicing design.',
    },
    jurisdictionNotes: {
      eu: 'MiCA is not the whole story; fund and distribution rules still matter.',
      sg: 'Project Guardian materials make Singapore an important pattern source.',
      hk: 'Controlled product perimeter and investor type remain central.',
      ch: 'Swiss custody and record models are relevant for safekeeping and segregation questions.',
    },
    relatedGlossary: ['nav', 'whitelisting', 'reconciliation'],
    relatedPatterns: ['tokenized-mmf-distribution'],
    relatedSimulations: ['tokenized-fund-subscription'],
    relatedControls: ['ctl-investor-eligibility', 'ctl-nav-governance', 'ctl-reconciliation'],
    sourceIds: ['mas-project-guardian', 'ubs-tokenize', 'chainlink-dta'],
    lastReviewed: '2026-03-18',
    reviewOwner: 'product-research',
    freshnessDays: 45,
  },
  {
    id: 'tokenized-bonds',
    title: 'Tokenized bonds and notes',
    summary: 'How issuance, settlement, safekeeping, and corporate actions change when debt instruments are tokenized.',
    plain: 'A tokenized bond still needs the same discipline around documentation, settlement, investor eligibility, and servicing.',
    practitioner: 'The useful questions are about issuance venue, DvP model, investor restrictions, custody assumptions, and paying-agent processes.',
    expert: 'The difficult points are legal wrapper alignment, identifier integrity, cash-leg coordination, transfer restriction logic, and default/restructuring branches.',
    whyItMatters: ['This is one of the most credible institutional tokenization use cases.', 'It highlights how “same economic exposure, different operational model” changes the control burden.'],
    misconceptions: ['Tokenization does not remove corporate action servicing.', 'A DLT venue does not erase legal wrapper questions.'],
    clientImpacts: {
      retail: 'Normally a controlled distribution topic rather than a broad retail product.',
      affluent: 'Client explanations need to separate wrapper, issuer risk, and transferability.',
      hnw: 'Suitability and liquidity expectations require care.',
      uhnw: 'Holding structure and succession still matter.',
      'family-office': 'Need clarity on wrapper, custodian, and valuation approach.',
      institutional: 'DvP, servicing, and operational resilience dominate.',
      'corporate-treasury': 'Relevant as an investment or funding pattern depending on context.',
      issuer: 'Primary product structuring use case.',
    },
    jurisdictionNotes: {
      uk: 'DSS context helps frame what is in sandbox scope.',
      ch: 'DLT venue and custody structure matter materially.',
      eu: 'Pilot-style and resilience overlays can affect the operating model.',
    },
    relatedGlossary: ['dvp', 'finality', 'segregation'],
    relatedPatterns: ['regulated-dlt-bond-issuance'],
    relatedSimulations: ['tokenized-bond-issuance'],
    relatedControls: ['ctl-legal-perimeter', 'ctl-corporate-actions', 'ctl-reconciliation'],
    sourceIds: ['boe-dss', 'sdx-official', 'ubs-tokenize'],
    lastReviewed: '2026-03-18',
    reviewOwner: 'product-research',
    freshnessDays: 45,
  },
  {
    id: 'tokenized-cash',
    title: 'Stablecoins, tokenized cash, and tokenized deposits',
    summary: 'Comparing settlement assets used in treasury, payments, and DvP or PvP designs.',
    plain: 'Not every tokenized money instrument works the same way or sits in the same legal bucket.',
    practitioner: 'A practical comparison needs to cover redemption rights, reserve model, operating window, whitelisting, and counterparty concentration.',
    expert: 'The critical distinctions are legal claim, transfer perimeter, confirmation and finality policy, prefunding burden, and failure handling.',
    whyItMatters: ['Treasury and settlement architecture depends on the settlement asset more than on the label.', 'The same product design can look credible or fragile depending on this choice.'],
    misconceptions: ['A stablecoin is not automatically equivalent to bank money.', 'Tokenized cash choices do not only affect speed; they change risk ownership.'],
    clientImpacts: {
      retail: 'Usually seen through product-safety and redemption-confidence questions.',
      affluent: 'Need plain language on claim structure and issuer risk.',
      hnw: 'Cross-border transfer and reporting questions matter.',
      uhnw: 'Wealth structures care about redemption certainty and operational control.',
      'family-office': 'Entity wrappers and signatory controls remain important.',
      institutional: 'Treasury, DvP, PvP, and prefunding design dominate.',
      'corporate-treasury': 'This is a primary use case.',
      issuer: 'Relevant as a distribution and settlement design dependency.',
    },
    jurisdictionNotes: {
      sg: 'Official stablecoin framework and Guardian references make Singapore an important comparator.',
      hk: 'Stablecoin licensing perimeter is central.',
      eu: 'EMT/FRT distinctions matter.',
      us: 'Commercial importance is high, but legal review remains mandatory.',
    },
    relatedGlossary: ['stablecoin', 'tokenized-deposit', 'pvp'],
    relatedPatterns: ['tokenized-cash-settlement'],
    relatedSimulations: ['tokenized-cash-payments'],
    relatedControls: ['ctl-liquidity-prefunding', 'ctl-screening', 'ctl-concentration'],
    sourceIds: ['mas-stablecoin', 'hkma-stablecoin', 'esma-mica', 'kinexys-digital-payments'],
    lastReviewed: '2026-03-18',
    reviewOwner: 'product-research',
    freshnessDays: 45,
  },
  {
    id: 'custody-governance',
    title: 'Custody and key governance',
    summary: 'Why custody design is usually the decisive control question in institutional digital-asset work.',
    plain: 'The core custody question is simple: who can move the asset, under what rules, and how is that evidenced?',
    practitioner: 'Good custody design covers segregation, approvals, recovery, delegation, and incident handling.',
    expert: 'Cross-border delegation, asset-location assumptions, bankruptcy treatment, MPC or HSM policy design, and recovery playbooks are the real depth areas.',
    whyItMatters: ['Many digital-asset initiatives fail trust tests because custody is hand-waved.', 'Institutional users care as much about evidence and recovery as about day-to-day safekeeping.'],
    misconceptions: ['Cold storage is not a full custody strategy.', 'Delegated custody is not merely an outsourcing line item.'],
    clientImpacts: {
      retail: 'Explanation must remain simple and avoid false security claims.',
      affluent: 'Transfer permissions and support expectations matter.',
      hnw: 'Asset recovery and advisor oversight become more relevant.',
      uhnw: 'Incapacity, death, and delegated access are central.',
      'family-office': 'Trust and wrapper governance intersect with custody design.',
      institutional: 'Segregation, resiliency, and outsourcing oversight dominate.',
      'corporate-treasury': 'Policy-controlled approvals and dual controls matter.',
      issuer: 'Primary design dependency for product launches.',
    },
    jurisdictionNotes: {
      ch: 'Swiss custody guidance is especially useful as an anchor.',
      eu: 'Operational resilience overlays matter alongside perimeter questions.',
      global: 'Global standards matter even when local regulation differs.',
    },
    relatedGlossary: ['segregation', 'cold-storage'],
    relatedPatterns: ['delegated-custody-model', 'family-office-governance-wrapper'],
    relatedSimulations: ['native-crypto-lifecycle', 'repo-collateral-mobilization'],
    relatedControls: ['ctl-custody-segregation', 'ctl-incident-response', 'ctl-outsourcing'],
    sourceIds: ['finma-guidance-01-2026', 'nist-csf-2'],
    lastReviewed: '2026-03-18',
    reviewOwner: 'risk-governance',
    freshnessDays: 45,
  },
  {
    id: 'wealth-planning',
    title: 'Wealth planning and family office overlays',
    summary: 'How digital-asset products change when trust structures, succession, governance, and recovery are in scope.',
    plain: 'Wealth planning asks different questions from institutional trading. It is about control, continuity, and family governance.',
    practitioner: 'Holding wrappers, signatory rights, incapacity, valuation, liquidity, and reporting all need explicit treatment.',
    expert: 'The hard parts are legally robust authority, break-glass recovery, advisor delegation, succession evidence, and concentration risk under stress.',
    whyItMatters: ['Wealth and family-office requirements are often ignored in generic digital-asset products.', 'This segment needs governance answers, not just market access.'],
    misconceptions: ['High-net-worth users do not only care about exposure.', 'A family office does not operate like a trading desk.'],
    clientImpacts: {
      retail: 'Mostly out of scope.',
      affluent: 'Some governance questions begin to appear.',
      hnw: 'Suitability, concentration, and reporting matter.',
      uhnw: 'Governance, estate planning, and recovery are mandatory.',
      'family-office': 'This is the core segment.',
      institutional: 'Mostly relevant as a contrast case.',
      'corporate-treasury': 'Generally irrelevant.',
      issuer: 'Important if designing wealth offerings.',
    },
    jurisdictionNotes: {
      ch: 'Custody and delegated custody analysis is useful.',
      uk: 'Wealth planning needs specialist follow-up for legal and tax wrappers.',
      sg: 'Institutional strength does not remove private-client governance questions.',
    },
    relatedGlossary: ['segregation', 'reconciliation'],
    relatedPatterns: ['family-office-governance-wrapper'],
    relatedSimulations: ['structured-product-lifecycle'],
    relatedControls: ['ctl-wealth-governance', 'ctl-custody-segregation'],
    sourceIds: ['finma-guidance-01-2026', 'ubs-tokenize'],
    lastReviewed: '2026-03-18',
    reviewOwner: 'wealth-research',
    freshnessDays: 60,
  },
];

export const journeys: Journey[] = [
  {
    id: 'wealth-management',
    title: 'Digital assets for wealth management',
    summary: 'Start with client-ready explanations, then layer on custody, suitability, and family governance.',
    audience: ['relationship managers', 'wealth planners', 'family office advisors'],
    stops: [
      { label: 'Native crypto exposure', href: '/learn/native-crypto-exposure/' },
      { label: 'Custody and key governance', href: '/learn/custody-governance/' },
      { label: 'Wealth planning', href: '/learn/wealth-planning/' },
      { label: 'Native crypto simulation', href: '/simulate/native-crypto-lifecycle/' },
    ],
  },
  {
    id: 'tokenized-funds',
    title: 'How tokenized funds work',
    summary: 'Walk through tokenized fund distribution, controlled transferability, and reconciliation.',
    audience: ['product', 'operations', 'institutional coverage'],
    stops: [
      { label: 'Tokenized funds', href: '/learn/tokenized-funds/' },
      { label: 'Singapore market pack', href: '/markets/sg/' },
      { label: 'Tokenized fund simulation', href: '/simulate/tokenized-fund-subscription/' },
      { label: 'Decision pack', href: '/studio/decision-pack/' },
    ],
  },
  {
    id: 'tokenized-bonds',
    title: 'How tokenized bonds are issued and serviced',
    summary: 'Cover issuance, DvP, servicing, and sandbox or venue considerations.',
    audience: ['origination', 'product', 'operations'],
    stops: [
      { label: 'Tokenized bonds', href: '/learn/tokenized-bonds/' },
      { label: 'United Kingdom market pack', href: '/markets/uk/' },
      { label: 'Bond issuance simulation', href: '/simulate/tokenized-bond-issuance/' },
    ],
  },
  {
    id: 'tokenized-cash',
    title: 'Settlement asset choices',
    summary: 'Compare stablecoins, tokenized deposits, and bank rails with control overlays.',
    audience: ['treasury', 'architecture', 'product'],
    stops: [
      { label: 'Tokenized cash', href: '/learn/tokenized-cash/' },
      { label: 'Networks', href: '/networks/' },
      { label: 'Treasury simulation', href: '/simulate/tokenized-cash-payments/' },
    ],
  },
];

export const jurisdictionPacks: JurisdictionPack[] = [
  {
    id: 'ch',
    label: 'Switzerland',
    status: 'tier1',
    summary: 'High-confidence market pack for custody, DLT venue, and institutional tokenization patterns.',
    authorities: [{ name: 'FINMA', url: 'https://www.finma.ch/en/' }],
    marketRelevance: ['Custody clarity', 'DLT market infrastructure', 'institutional issuance'],
    coreTopics: ['Custody', 'Segregation', 'Delegated custody', 'DLT venues'],
    activityMap: ['Issuance', 'Custody', 'Settlement', 'Venue-based trading'],
    controlHotspots: ['Delegated custody', 'Segregation evidence', 'Cross-border sub-custody'],
    simulationOverlays: ['delegated-custody', 'dlt-venue'],
    defaultWarnings: ['Foreign delegation and insolvency treatment need explicit review.'],
    confidence: 'high',
    changeStatus: 'final',
    sourceIds: ['finma-guidance-01-2026', 'sdx-official'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'eu',
    label: 'European Union',
    status: 'tier1',
    summary: 'Deep pack for MiCA and DORA overlays across custody, service roles, and resilience.',
    authorities: [{ name: 'ESMA', url: 'https://www.esma.europa.eu/' }],
    marketRelevance: ['MiCA service perimeter', 'DORA resilience', 'fund tokenization'],
    coreTopics: ['CASP roles', 'EMT and FRT distinctions', 'Order and record expectations', 'Operational resilience'],
    activityMap: ['Custody', 'Distribution', 'Trading', 'Reporting'],
    controlHotspots: ['Role perimeter', 'Record keeping', 'Incident handling'],
    simulationOverlays: ['dora', 'casp-role', 'whitepaper'],
    defaultWarnings: ['MiCA does not replace product-specific, fund, or securities analysis.'],
    confidence: 'high',
    changeStatus: 'final',
    sourceIds: ['esma-mica', 'eu-dora'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'uk',
    label: 'United Kingdom',
    status: 'tier1',
    summary: 'Deep pack for DSS boundaries and future-crypto-regime caution.',
    authorities: [{ name: 'Bank of England', url: 'https://www.bankofengland.co.uk/' }, { name: 'FCA', url: 'https://www.fca.org.uk/' }],
    marketRelevance: ['Digital securities sandbox', 'future crypto regime'],
    coreTopics: ['Sandbox scope', 'Digital securities vs unbacked crypto', 'Pilot-to-production thinking'],
    activityMap: ['Sandbox issuance', 'DLT market infrastructure', 'controlled experimentation'],
    controlHotspots: ['Scope boundaries', 'Legal review for future regime assumptions'],
    simulationOverlays: ['dss-allowed', 'future-regime-caution'],
    defaultWarnings: ['Do not treat sandbox participation as a general launch permission.'],
    confidence: 'high',
    changeStatus: 'sandbox',
    sourceIds: ['boe-dss', 'fca-future-crypto'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'sg',
    label: 'Singapore',
    status: 'tier1',
    summary: 'Deep pack for tokenized funds, institutional tokenization, and stablecoin comparisons.',
    authorities: [{ name: 'MAS', url: 'https://www.mas.gov.sg/' }],
    marketRelevance: ['Project Guardian', 'tokenized funds', 'stablecoin regulation'],
    coreTopics: ['Commercialisation patterns', 'Settlement asset choices', 'Fund lifecycle design'],
    activityMap: ['Funds', 'Payments', 'Institutional tokenization'],
    controlHotspots: ['Wallet governance', 'Stablecoin perimeter', 'Fund lifecycle controls'],
    simulationOverlays: ['guardian-fund', 'stablecoin-guardrails'],
    defaultWarnings: ['Project outputs do not remove the need for institution-specific approvals and controls.'],
    confidence: 'high',
    changeStatus: 'statement',
    sourceIds: ['mas-project-guardian', 'mas-stablecoin'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'hk',
    label: 'Hong Kong',
    status: 'tier1',
    summary: 'Deep pack for virtual-asset roadmap and fiat-referenced token perimeter.',
    authorities: [{ name: 'SFC', url: 'https://www.sfc.hk/' }, { name: 'HKMA', url: 'https://www.hkma.gov.hk/' }],
    marketRelevance: ['VA roadmap', 'stablecoin regime', 'platform permissions'],
    coreTopics: ['Roadmap pillars', 'Stablecoin licensing', 'Platform controls'],
    activityMap: ['Trading', 'Stablecoin issuance', 'Custody and dealer analysis'],
    controlHotspots: ['Product eligibility', 'Platform scope', 'Dealer and custodian review'],
    simulationOverlays: ['frt-branch', 'vatp-branch'],
    defaultWarnings: ['Product access and platform scope can change materially by client and product type.'],
    confidence: 'high',
    changeStatus: 'statement',
    sourceIds: ['sfc-aspire', 'hkma-stablecoin'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'us',
    label: 'United States',
    status: 'tier2',
    summary: 'Commercially unavoidable market with significant ongoing interpretive and launch-review complexity.',
    authorities: [{ name: 'SEC', url: 'https://www.sec.gov/' }],
    marketRelevance: ['Commercial importance', 'changing interpretive posture'],
    coreTopics: ['Securities-law analysis', 'banking-agency posture', 'launch review'],
    activityMap: ['Advisory', 'structuring', 'legal review'],
    controlHotspots: ['Specialist legal review', 'distribution restrictions'],
    simulationOverlays: ['us-review-required'],
    defaultWarnings: ['Treat US launch assumptions as legal-review-required by default.'],
    confidence: 'medium',
    changeStatus: 'statement',
    sourceIds: ['sec-crypto-2026'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'adgm',
    label: 'UAE / ADGM',
    status: 'tier2',
    summary: 'Regional reference market for regulated digital-asset and fiat-referenced-token structuring.',
    authorities: [{ name: 'ADGM', url: 'https://www.adgm.com/' }],
    marketRelevance: ['Regional hub', 'fiat-referenced token regime'],
    coreTopics: ['Regional structuring', 'tokenized cash'],
    activityMap: ['Payments', 'regulated activities'],
    controlHotspots: ['Regime mapping', 'counterparty and perimeter checks'],
    simulationOverlays: ['adgm-frt'],
    defaultWarnings: ['Cross-border marketing and structuring still need case-specific review.'],
    confidence: 'medium',
    changeStatus: 'final',
    sourceIds: ['adgm-frt'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'jp',
    label: 'Japan',
    status: 'tier2',
    summary: 'Cautious APAC reference pack for stablecoin and crypto-asset regulatory framing.',
    authorities: [{ name: 'FSA Japan', url: 'https://www.fsa.go.jp/en/' }],
    marketRelevance: ['APAC comparator', 'payment-services relevance'],
    coreTopics: ['Stablecoin and crypto systems', 'travel-rule relevance'],
    activityMap: ['Payments', 'regulated services'],
    controlHotspots: ['Specialist review', 'framework mapping'],
    simulationOverlays: ['jp-review-required'],
    defaultWarnings: ['Treat Japan as a specialist review jurisdiction in this first release.'],
    confidence: 'medium',
    changeStatus: 'statement',
    sourceIds: ['japan-fsa-2025'],
    lastReviewed: '2026-03-18',
  },
];

export const networkProfiles: NetworkProfile[] = [
  {
    id: 'public-chain-pattern',
    label: 'Public-chain pattern',
    category: 'public-chain',
    summary: 'Generic pattern for open networks with public validation and variable confidentiality controls.',
    assetSupport: ['Native crypto', 'tokenized assets', 'stablecoins'],
    participantModel: 'Open or permissioned-at-application-layer participation.',
    settlementModel: 'On-chain settlement with network-dependent confirmation and finality assumptions.',
    identityModel: 'Pseudonymous by default with overlay identity controls.',
    privacyModel: 'Transaction data usually visible unless overlay privacy tools are added.',
    finalityProfile: 'Depends on network design and risk policy.',
    operatingWindow: 'Typically continuous, but supporting teams and rails may not be.',
    controlConsiderations: ['Wallet whitelisting', 'Screening', 'Operational support coverage'],
    interoperabilityNotes: ['Strong composability, but governance and data leakage risks matter.'],
    sourceIds: ['chainlink-dta'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'permissioned-chain-pattern',
    label: 'Permissioned-chain pattern',
    category: 'permissioned-chain',
    summary: 'Generic pattern for whitelisted participant sets and controlled data sharing.',
    assetSupport: ['Tokenized funds', 'bonds', 'controlled cash'],
    participantModel: 'Known participants under a network rulebook.',
    settlementModel: 'Controlled transfer and settlement with governance-defined workflows.',
    identityModel: 'Built-in participant identity and whitelisting.',
    privacyModel: 'Higher control over data exposure.',
    finalityProfile: 'Governance-led and easier to align with operating procedures.',
    operatingWindow: 'Usually controlled and aligned to participant support models.',
    controlConsiderations: ['Concentration risk', 'Exit portability', 'Operator dependency'],
    interoperabilityNotes: ['Interoperability often depends on bespoke connectors.'],
    sourceIds: ['sdx-official'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'sdx',
    label: 'SDX',
    category: 'fmi',
    summary: 'Reference point for a regulated DLT venue and settlement environment.',
    assetSupport: ['Tokenized bonds', 'digital securities'],
    participantModel: 'Institutional market participants under venue rules.',
    settlementModel: 'Venue-linked issuance and settlement model.',
    identityModel: 'Institutional participant onboarding and rulebook controls.',
    privacyModel: 'Controlled market-infrastructure model.',
    finalityProfile: 'Defined through venue and settlement design.',
    operatingWindow: 'Institutional operating model.',
    controlConsiderations: ['Venue dependency', 'Participant onboarding', 'Post-trade controls'],
    interoperabilityNotes: ['Strong reference for regulated-infrastructure comparisons.'],
    sourceIds: ['sdx-official'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'kinexys',
    label: 'Kinexys Digital Payments',
    category: 'bank-rail',
    summary: 'Reference pattern for bank-run digital settlement and treasury use cases.',
    assetSupport: ['Tokenized cash', 'treasury settlement'],
    participantModel: 'Bank and approved participant model.',
    settlementModel: 'Bank-linked controlled digital payments.',
    identityModel: 'Institutional account and permissions framework.',
    privacyModel: 'Controlled enterprise environment.',
    finalityProfile: 'Operationally defined within the rail.',
    operatingWindow: 'Aims at extended operating utility rather than open public access.',
    controlConsiderations: ['Bank dependency', 'Prefunding', 'Counterparty access'],
    interoperabilityNotes: ['Useful comparator against open-network stablecoin models.'],
    sourceIds: ['kinexys-digital-payments'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'ubs-tokenize-network',
    label: 'UBS Tokenize',
    category: 'tokenization-stack',
    summary: 'Market exemplar for bank-led tokenization across multiple product families.',
    assetSupport: ['Bonds', 'funds', 'structured products'],
    participantModel: 'Institutional and bank-led product distribution pattern.',
    settlementModel: 'Varies by product and target market.',
    identityModel: 'Institutional client and counterparty controls.',
    privacyModel: 'Product-specific.',
    finalityProfile: 'Dependent on selected network and servicing model.',
    operatingWindow: 'Institutional product cadence.',
    controlConsiderations: ['Operating model complexity', 'Multi-product governance'],
    interoperabilityNotes: ['Best read as a pattern library reference, not a single network answer.'],
    sourceIds: ['ubs-tokenize'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'chainlink-dta-network',
    label: 'Chainlink DTA',
    category: 'middleware',
    summary: 'Reference pattern for tokenized fund data synchronization and transfer-agent style workflows.',
    assetSupport: ['Tokenized funds'],
    participantModel: 'Transfer-agent and administrator style coordination.',
    settlementModel: 'Middleware and synchronization pattern rather than a standalone rail.',
    identityModel: 'Depends on host product controls.',
    privacyModel: 'Depends on deployment and connected systems.',
    finalityProfile: 'Inherits finality characteristics from connected networks and records.',
    operatingWindow: 'Operational workflow driven.',
    controlConsiderations: ['Source-of-truth policy', 'Data synchronization', 'Admin dependency'],
    interoperabilityNotes: ['Useful when comparing on-chain and off-chain record dominance.'],
    sourceIds: ['chainlink-dta'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'sg-forge',
    label: 'SG-FORGE CoinVertible',
    category: 'bank-rail',
    summary: 'Reference point for regulated stablecoin and tokenized cash discussions.',
    assetSupport: ['Stablecoins', 'treasury settlement'],
    participantModel: 'Regulated issuer pattern.',
    settlementModel: 'Issuer-backed tokenized money flow.',
    identityModel: 'Controlled issuance and counterparty access.',
    privacyModel: 'Regulated enterprise controls.',
    finalityProfile: 'Depends on network and redemption design.',
    operatingWindow: 'Institutional operating model.',
    controlConsiderations: ['Issuer risk', 'Redemption governance', 'Counterparty perimeter'],
    interoperabilityNotes: ['Useful comparator against tokenized deposits and bank rails.'],
    sourceIds: ['ubs-tokenize'],
    lastReviewed: '2026-03-18',
  },
  {
    id: 'digift',
    label: 'DigiFT',
    category: 'fmi',
    summary: 'Reference point for venue-mediated tokenized fund and asset access.',
    assetSupport: ['Tokenized funds', 'digital assets'],
    participantModel: 'Venue participation model.',
    settlementModel: 'Venue and access-layer mediated.',
    identityModel: 'Participant onboarding required.',
    privacyModel: 'Venue-controlled.',
    finalityProfile: 'Depends on venue and connected rails.',
    operatingWindow: 'Institutional market model.',
    controlConsiderations: ['Venue dependency', 'Product permissioning'],
    interoperabilityNotes: ['Best compared against bilateral and bank-led models.'],
    sourceIds: ['digift-official'],
    lastReviewed: '2026-03-18',
  },
];

export const patterns: Pattern[] = [
  {
    id: 'tokenized-mmf-distribution',
    title: 'Tokenized money market fund distribution',
    summary: 'Controlled distribution, wallet whitelisting, NAV-driven mint and burn, and synchronized records.',
    clientSegments: ['institutional', 'family-office', 'corporate-treasury'],
    assetFamily: 'Tokenized fund',
    legalWrapper: 'Fund unit',
    settlementAsset: 'Fiat, stablecoin, or tokenized deposit',
    custodyModel: 'Whitelisted wallet plus custodian or delegated operator',
    networkType: 'Permissioned or controlled public-chain overlay',
    primaryObjective: 'Faster distribution and operational programmability without removing controls',
    controlHotspots: ['Investor eligibility', 'NAV governance', 'reconciliation'],
    sourceIds: ['mas-project-guardian', 'chainlink-dta', 'digift-official'],
  },
  {
    id: 'regulated-dlt-bond-issuance',
    title: 'Tokenized bond issuance on regulated or controlled venue',
    summary: 'Documentation, issuance, DvP settlement, safekeeping, and servicing across a controlled market-infrastructure model.',
    clientSegments: ['institutional', 'issuer'],
    assetFamily: 'Tokenized bond',
    legalWrapper: 'Debt security',
    settlementAsset: 'Cash leg or tokenized cash',
    custodyModel: 'Custodian or venue-mediated holding model',
    networkType: 'FMI or permissioned venue',
    primaryObjective: 'Institutional issuance efficiency with controlled servicing',
    controlHotspots: ['Legal perimeter', 'DvP model', 'corporate actions'],
    sourceIds: ['sdx-official', 'boe-dss', 'ubs-tokenize'],
  },
  {
    id: 'tokenized-cash-settlement',
    title: 'Tokenized cash settlement',
    summary: 'Treasury, settlement, and cross-border movement using stablecoins, tokenized deposits, or bank rails.',
    clientSegments: ['institutional', 'corporate-treasury'],
    assetFamily: 'Tokenized cash',
    legalWrapper: 'Stablecoin or deposit claim',
    settlementAsset: 'Tokenized money instrument',
    custodyModel: 'Institutional wallet or account control',
    networkType: 'Bank rail or controlled chain',
    primaryObjective: 'Extended operating utility and improved settlement design',
    controlHotspots: ['Prefunding', 'issuer risk', 'screening'],
    sourceIds: ['kinexys-digital-payments', 'mas-stablecoin', 'hkma-stablecoin'],
  },
  {
    id: 'delegated-custody-model',
    title: 'Delegated custody and transfer-control model',
    summary: 'Institutional custody with segregation, approvals, delegated operation, and incident response.',
    clientSegments: ['hnw', 'uhnw', 'family-office', 'institutional'],
    assetFamily: 'Custody model',
    legalWrapper: 'Custody arrangement',
    settlementAsset: 'N/A',
    custodyModel: 'Delegated with policy controls',
    networkType: 'Any',
    primaryObjective: 'Operational safety, recovery, and evidencing',
    controlHotspots: ['Segregation', 'outsourcing', 'incident response'],
    sourceIds: ['finma-guidance-01-2026', 'nist-csf-2'],
  },
  {
    id: 'family-office-governance-wrapper',
    title: 'Family office governance wrapper',
    summary: 'Holding through trust, company, or foundation structures with explicit signatory and recovery logic.',
    clientSegments: ['uhnw', 'family-office'],
    assetFamily: 'Wealth planning',
    legalWrapper: 'Trust or corporate wrapper',
    settlementAsset: 'Varies',
    custodyModel: 'Delegated or shared governance custody',
    networkType: 'Any',
    primaryObjective: 'Continuity and governance rather than trading speed',
    controlHotspots: ['Authority evidence', 'recovery', 'liquidity planning'],
    sourceIds: ['finma-guidance-01-2026', 'ubs-tokenize'],
  },
  {
    id: 'repo-collateral-pattern',
    title: 'Repo and collateral mobilization',
    summary: 'Use of digital assets or tokenized securities as collateral with valuation, margin, and unwind discipline.',
    clientSegments: ['institutional', 'corporate-treasury'],
    assetFamily: 'Repo and collateral',
    legalWrapper: 'Repo or collateral arrangement',
    settlementAsset: 'Cash or tokenized cash',
    custodyModel: 'Triparty or bilateral control model',
    networkType: 'Controlled venue or permissioned settlement rail',
    primaryObjective: 'Intraday liquidity and collateral mobility',
    controlHotspots: ['Valuation', 'legal enforceability', 'default handling'],
    sourceIds: ['sdx-official', 'basel-crypto'],
  },
];

export const controls: Control[] = [
  {
    id: 'ctl-suitability',
    domain: 'Client suitability and disclosure',
    title: 'Assess product fit and disclosure burden',
    objective: 'Ensure the selected product is appropriate for the target segment and that core cautions are evidenced.',
    whyItMatters: 'Many digital-asset harms arise from mismatched client understanding, product complexity, or liquidity expectations.',
    appliesWhen: ['Any client-facing exposure', 'Structured products', 'Direct crypto'],
    evidenceExamples: ['Suitability rationale', 'Client-ready risk explanation', 'Segment restrictions'],
    severityIfMissing: 'high',
    ownerHints: ['Front office', 'Product', 'Compliance'],
    sourceIds: ['sec-crypto-2026', 'esma-mica'],
    relatedRules: ['rule-retail-structured-products'],
    relatedSimulations: ['native-crypto-lifecycle', 'structured-product-lifecycle'],
  },
  {
    id: 'ctl-custody-segregation',
    domain: 'Custody and safekeeping',
    title: 'Evidence segregation and delegated-custody boundaries',
    objective: 'Show who controls assets, where they sit, and how client and house assets are separated.',
    whyItMatters: 'Custody failures quickly become trust failures in institutional and private-client use cases.',
    appliesWhen: ['Custody', 'Transfers', 'Delegation'],
    evidenceExamples: ['Account structure map', 'Delegation agreement', 'Insolvency treatment note'],
    severityIfMissing: 'critical',
    ownerHints: ['Custody', 'Legal', 'Operations'],
    sourceIds: ['finma-guidance-01-2026'],
    relatedRules: ['rule-high-value-custody'],
    relatedSimulations: ['native-crypto-lifecycle', 'repo-collateral-mobilization'],
  },
  {
    id: 'ctl-travel-rule',
    domain: 'AML / sanctions / travel rule',
    title: 'Apply transfer screening and Travel Rule checks',
    objective: 'Ensure outbound and inbound transfer workflows include screening and data-sharing controls when required.',
    whyItMatters: 'Transferability is one of the main points where digital-asset risk becomes operationally real.',
    appliesWhen: ['External transfer', 'Wallet attestation', 'Cross-border payments'],
    evidenceExamples: ['Screening checkpoint', 'Travel Rule routing note', 'Address attestation result'],
    severityIfMissing: 'critical',
    ownerHints: ['Compliance', 'Operations'],
    sourceIds: ['fatf-vasp-2025'],
    relatedRules: ['rule-external-transfers'],
    relatedSimulations: ['native-crypto-lifecycle', 'tokenized-cash-payments'],
  },
  {
    id: 'ctl-investor-eligibility',
    domain: 'Distribution and eligibility',
    title: 'Verify investor eligibility and class restrictions',
    objective: 'Prevent subscriptions and transfers that violate class, jurisdiction, or target-investor limits.',
    whyItMatters: 'Controlled distribution is central in tokenized fund and securities patterns.',
    appliesWhen: ['Tokenized funds', 'Tokenized bonds'],
    evidenceExamples: ['Eligibility decision', 'Wallet whitelist evidence', 'Class restriction note'],
    severityIfMissing: 'critical',
    ownerHints: ['Distributor', 'Transfer agent', 'Compliance'],
    sourceIds: ['mas-project-guardian', 'chainlink-dta'],
    relatedRules: ['rule-fund-wallet-whitelist'],
    relatedSimulations: ['tokenized-fund-subscription', 'tokenized-bond-issuance'],
  },
  {
    id: 'ctl-nav-governance',
    domain: 'Valuation and records',
    title: 'Govern NAV, pricing, and stale-data handling',
    objective: 'Ensure mint, burn, fee, and reporting flows depend on an explicit pricing and stale-data policy.',
    whyItMatters: 'A tokenized fund with weak NAV governance is not operationally trustworthy.',
    appliesWhen: ['Tokenized funds'],
    evidenceExamples: ['NAV source policy', 'Cut-off policy', 'Stale NAV escalation'],
    severityIfMissing: 'high',
    ownerHints: ['Fund administrator', 'Operations', 'Risk'],
    sourceIds: ['mas-project-guardian', 'chainlink-dta'],
    relatedRules: ['rule-nav-staleness'],
    relatedSimulations: ['tokenized-fund-subscription'],
  },
  {
    id: 'ctl-reconciliation',
    domain: 'Operations and record keeping',
    title: 'Reconcile on-chain and off-chain records',
    objective: 'Maintain a defined source-of-truth policy and mismatch escalation for tokenized workflows.',
    whyItMatters: 'Operational mismatch is one of the most common failure modes in hybrid architectures.',
    appliesWhen: ['Hybrid tokenization workflows', 'Tokenized funds', 'Bonds'],
    evidenceExamples: ['Reconciliation policy', 'Exception log', 'Source-of-truth statement'],
    severityIfMissing: 'critical',
    ownerHints: ['Operations', 'Technology', 'Reporting'],
    sourceIds: ['chainlink-dta'],
    relatedRules: ['rule-hybrid-recordkeeping'],
    relatedSimulations: ['tokenized-fund-subscription', 'tokenized-bond-issuance'],
  },
  {
    id: 'ctl-corporate-actions',
    domain: 'Servicing and corporate actions',
    title: 'Govern coupons, record dates, and servicing exceptions',
    objective: 'Ensure lifecycle events such as coupons, calls, or maturity payments are aligned to records and investor communications.',
    whyItMatters: 'Tokenization does not remove paying-agent, servicing, or record-date risk.',
    appliesWhen: ['Tokenized bonds', 'Servicing workflows'],
    evidenceExamples: ['Corporate action calendar', 'Record date process', 'Investor notice template'],
    severityIfMissing: 'high',
    ownerHints: ['Asset servicing', 'Operations', 'Legal'],
    sourceIds: ['sdx-official', 'boe-dss'],
    relatedRules: [],
    relatedSimulations: ['tokenized-bond-issuance'],
  },
  {
    id: 'ctl-screening',
    domain: 'AML / sanctions / screening',
    title: 'Apply sanctions and counterparty screening',
    objective: 'Run and evidence sanctions, AML, and counterparty screens before sensitive transfers and settlements.',
    whyItMatters: 'Treasury and transfer use cases still need strong screening even when they are not classic retail transfers.',
    appliesWhen: ['Payments', 'Cross-border movement', 'External transfers'],
    evidenceExamples: ['Screening result', 'Counterparty approval', 'Escalation note'],
    severityIfMissing: 'critical',
    ownerHints: ['Compliance', 'Operations'],
    sourceIds: ['fatf-vasp-2025'],
    relatedRules: ['rule-external-transfers'],
    relatedSimulations: ['native-crypto-lifecycle', 'tokenized-cash-payments'],
  },
  {
    id: 'ctl-legal-perimeter',
    domain: 'Legal perimeter',
    title: 'Map the legal wrapper and perimeter before launch',
    objective: 'Force explicit classification and launch-review checkpoints where product perimeter is uncertain.',
    whyItMatters: 'Weak legal framing makes every later control appear more certain than it really is.',
    appliesWhen: ['New product', 'Jurisdiction expansion', 'Tokenized securities'],
    evidenceExamples: ['Perimeter memo', 'Legal review gate', 'Jurisdiction comparison'],
    severityIfMissing: 'critical',
    ownerHints: ['Legal', 'Product'],
    sourceIds: ['esma-mica', 'boe-dss', 'sec-crypto-2026'],
    relatedRules: ['rule-us-review-default', 'rule-uk-dss-scope'],
    relatedSimulations: ['tokenized-bond-issuance', 'structured-product-lifecycle'],
  },
  {
    id: 'ctl-liquidity-prefunding',
    domain: 'Treasury and liquidity',
    title: 'Model prefunding, liquidity, and intraday limits',
    objective: 'Show how the chosen settlement asset and rail affect funding, limits, and failure handling.',
    whyItMatters: 'Treasury designs can look attractive until prefunding and outage handling are made explicit.',
    appliesWhen: ['Payments', 'DvP', 'PvP', 'Repo'],
    evidenceExamples: ['Prefunding policy', 'Intraday limit table', 'Failover steps'],
    severityIfMissing: 'high',
    ownerHints: ['Treasury', 'Operations', 'Risk'],
    sourceIds: ['kinexys-digital-payments', 'basel-crypto'],
    relatedRules: ['rule-high-latency-overlay'],
    relatedSimulations: ['tokenized-cash-payments', 'repo-collateral-mobilization'],
  },
  {
    id: 'ctl-concentration',
    domain: 'Third-party and concentration risk',
    title: 'Assess issuer, vendor, and venue concentration',
    objective: 'Make dependency concentration visible when a product depends heavily on one provider or rail.',
    whyItMatters: 'Static product comparisons often hide the exit and failover cost of vendor concentration.',
    appliesWhen: ['Bank rails', 'Single-custodian models', 'Venue-centric designs'],
    evidenceExamples: ['Dependency map', 'Exit portability note', 'Fallback design'],
    severityIfMissing: 'high',
    ownerHints: ['Risk', 'Architecture', 'Operations'],
    sourceIds: ['nist-csf-2'],
    relatedRules: ['rule-concentration-warning'],
    relatedSimulations: ['tokenized-cash-payments', 'repo-collateral-mobilization'],
  },
  {
    id: 'ctl-incident-response',
    domain: 'Operational resilience',
    title: 'Prepare incident communication and recovery playbooks',
    objective: 'Ensure key compromise, outage, sanctions alerts, and data mismatches have explicit response paths.',
    whyItMatters: 'Digital-asset operations fail loudly; response quality matters as much as preventative controls.',
    appliesWhen: ['Custody', 'Hybrid tokenization', 'Payments'],
    evidenceExamples: ['Runbook', 'Escalation matrix', 'Client communication template'],
    severityIfMissing: 'critical',
    ownerHints: ['Operations', 'Cyber', 'Communications'],
    sourceIds: ['eu-dora', 'nist-csf-2'],
    relatedRules: ['rule-incident-coverage'],
    relatedSimulations: ['native-crypto-lifecycle', 'tokenized-fund-subscription', 'tokenized-cash-payments'],
  },
  {
    id: 'ctl-wealth-governance',
    domain: 'Wealth governance',
    title: 'Evidence authority, succession, and recovery for complex holdings',
    objective: 'Support family-office and UHNW workflows with explicit governance and continuity controls.',
    whyItMatters: 'Private-client digital-asset designs break down if authority and recovery are not explicit.',
    appliesWhen: ['UHNW', 'Family office', 'Trust wrappers'],
    evidenceExamples: ['Signatory matrix', 'Incapacity plan', 'Succession question list'],
    severityIfMissing: 'high',
    ownerHints: ['Wealth planning', 'Legal', 'Front office'],
    sourceIds: ['finma-guidance-01-2026'],
    relatedRules: ['rule-family-office-governance'],
    relatedSimulations: ['structured-product-lifecycle', 'native-crypto-lifecycle'],
  },
  {
    id: 'ctl-outsourcing',
    domain: 'Third-party oversight',
    title: 'Govern delegated operators and sub-custodians',
    objective: 'Define oversight, reporting, and fallback expectations for external operators.',
    whyItMatters: 'Delegation can solve for capability but add hidden control and insolvency risk.',
    appliesWhen: ['Delegated custody', 'Managed tokenization stack'],
    evidenceExamples: ['Outsourcing assessment', 'Oversight cadence', 'Fallback option'],
    severityIfMissing: 'high',
    ownerHints: ['Vendor management', 'Legal', 'Risk'],
    sourceIds: ['finma-guidance-01-2026', 'eu-dora'],
    relatedRules: ['rule-outsourced-custody'],
    relatedSimulations: ['native-crypto-lifecycle', 'repo-collateral-mobilization'],
  },
];

const standardStepSet = (
  base: Array<[string, string, string, string[], string[]]>,
): SimulationScenario['steps'] =>
  base.map(([id, title, lane, documents, controlsForStep]) => ({
    id,
    title,
    lane,
    summary: title,
    documents,
    controls: controlsForStep,
    sources: [],
  }));

export const simulations: SimulationScenario[] = [
  {
    id: 'native-crypto-lifecycle',
    title: 'Native crypto onboarding, custody, transfer, and reporting',
    summary: 'Direct crypto lifecycle with suitability, onboarding, trading, safekeeping, transfer, and reporting branches.',
    assetFamily: 'Native crypto',
    clientSegments: ['retail', 'hnw', 'uhnw', 'family-office', 'institutional'],
    jurisdictions: ['ch', 'eu', 'uk', 'sg', 'hk', 'us'],
    actors: ['Client', 'RM / advisor', 'Compliance', 'Custody', 'Venue', 'Operations', 'Reporting'],
    variables: [
      { id: 'custodyModel', label: 'Custody model', options: ['Bank custody', 'Third-party custody', 'Hybrid'], defaultValue: 'Bank custody' },
      { id: 'transferMode', label: 'Transfer mode', options: ['No transfer out', 'Internal transfer', 'External wallet'], defaultValue: 'External wallet' },
      { id: 'latencyNeed', label: 'Latency need', options: ['low', 'medium', 'high'], defaultValue: 'medium' },
    ],
    happyPath: ['Intent', 'Eligibility', 'Onboarding', 'Execution', 'Safekeeping', 'Transfer', 'Reporting'],
    operationalArtifacts: ['Client explanation', 'Transfer checklist', 'Risk heatmap', 'JSON state snapshot'],
    sourceIds: ['finma-guidance-01-2026', 'fatf-vasp-2025', 'sec-crypto-2026'],
    steps: standardStepSet([
      ['intent', 'Capture client intent and account wrapper', 'Front office', ['Intent note'], ['ctl-suitability', 'ctl-wealth-governance']],
      ['eligibility', 'Assess product eligibility and classification', 'Compliance', ['Eligibility record'], ['ctl-suitability', 'ctl-legal-perimeter']],
      ['onboarding', 'Complete KYC, source-of-funds, and wallet setup', 'Operations', ['KYC pack', 'Wallet setup'], ['ctl-travel-rule', 'ctl-custody-segregation']],
      ['execution', 'Execute trade and allocate holdings', 'Trading', ['Order record'], ['ctl-reconciliation']],
      ['safekeeping', 'Apply custody and approval policy', 'Custody', ['Custody policy'], ['ctl-custody-segregation', 'ctl-outsourcing']],
      ['transfer', 'Perform screened transfer or internal movement', 'Operations', ['Transfer evidence'], ['ctl-travel-rule', 'ctl-incident-response']],
      ['reporting', 'Produce statements, valuation, and review outputs', 'Reporting', ['Statement', 'Review note'], ['ctl-reconciliation']],
    ]),
    branches: [
      { id: 'unsuitable', label: 'Unsuitable client', trigger: 'Selected segment cannot support the product complexity.', impact: ['Pause the journey and route to client-ready explanation.'], addedWarnings: ['Do not proceed without specialist suitability review.'], addedControls: ['ctl-suitability'], addedArtifacts: ['Client caution memo'] },
      { id: 'sanctions-hit', label: 'Sanctions or adverse media hit', trigger: 'Screening returns a material flag.', impact: ['Escalate to compliance and freeze transfer path.'], addedWarnings: ['Outbound movement blocked pending review.'], addedControls: ['ctl-travel-rule', 'ctl-incident-response'], addedArtifacts: ['Escalation log'] },
      { id: 'wallet-attestation-fail', label: 'Wallet attestation failed', trigger: 'Ownership or wallet approval cannot be evidenced.', impact: ['Disable transfer out and retain in custody.'], addedWarnings: ['External transfer path removed.'], addedControls: ['ctl-travel-rule'], addedArtifacts: ['Wallet attestation exception'] },
      { id: 'custody-incident', label: 'Custody provider incident', trigger: 'Provider suspends withdrawals or reports compromise.', impact: ['Activate recovery playbook and client communications.'], addedWarnings: ['Operational resilience branch active.'], addedControls: ['ctl-incident-response', 'ctl-outsourcing'], addedArtifacts: ['Incident response pack'] },
      { id: 'family-governance', label: 'Incapacity or death branch', trigger: 'UHNW or family-office governance event occurs.', impact: ['Require authority and succession evidence before movement.'], addedWarnings: ['Do not assume advisor authority.'], addedControls: ['ctl-wealth-governance'], addedArtifacts: ['Succession checklist'] },
    ],
  },
  {
    id: 'tokenized-fund-subscription',
    title: 'Tokenized money market fund subscription and redemption',
    summary: 'Investor onboarding, wallet whitelisting, subscription, mint, holding, redemption, and reconciliation.',
    assetFamily: 'Tokenized fund',
    clientSegments: ['family-office', 'institutional', 'corporate-treasury'],
    jurisdictions: ['eu', 'sg', 'hk', 'ch'],
    actors: ['Investor', 'Distributor', 'Compliance', 'Fund manager', 'Transfer agent', 'Custodian', 'Administrator'],
    variables: [
      { id: 'settlementAsset', label: 'Settlement asset', options: ['Fiat', 'Stablecoin', 'Tokenized deposit'], defaultValue: 'Tokenized deposit' },
      { id: 'registryModel', label: 'Registry model', options: ['Off-chain dominant', 'Hybrid synchronized', 'On-chain dominant'], defaultValue: 'Hybrid synchronized' },
    ],
    happyPath: ['Eligibility', 'Whitelist', 'Subscription', 'NAV strike', 'Mint', 'Hold', 'Redeem'],
    operationalArtifacts: ['Sequence diagram', 'Control checklist', 'Architecture memo', 'JSON state snapshot'],
    sourceIds: ['mas-project-guardian', 'chainlink-dta', 'ubs-tokenize'],
    steps: standardStepSet([
      ['eligibility', 'Check investor eligibility and class restrictions', 'Distribution', ['Eligibility note'], ['ctl-investor-eligibility']],
      ['whitelist', 'Bind identity to whitelisted wallet', 'Operations', ['Whitelist record'], ['ctl-investor-eligibility']],
      ['subscription', 'Capture subscription and funding instructions', 'Distributor', ['Subscription order'], ['ctl-nav-governance']],
      ['nav', 'Strike or confirm NAV and validate cut-off', 'Administrator', ['NAV confirmation'], ['ctl-nav-governance']],
      ['mint', 'Mint and allocate fund tokens', 'Tokenization stack', ['Mint log'], ['ctl-reconciliation']],
      ['hold', 'Hold, report, and monitor transfers', 'Custody', ['Holding report'], ['ctl-reconciliation']],
      ['redeem', 'Burn, settle cash, and close reconciliation loop', 'Operations', ['Redemption record'], ['ctl-reconciliation', 'ctl-incident-response']],
    ]),
    branches: [
      { id: 'wallet-not-whitelisted', label: 'Wallet not whitelisted', trigger: 'Subscription wallet is not approved.', impact: ['Pause mint flow until identity binding is complete.'], addedWarnings: ['No token delivery allowed.'], addedControls: ['ctl-investor-eligibility'], addedArtifacts: ['Whitelist exception'] },
      { id: 'nav-stale', label: 'NAV stale or unavailable', trigger: 'Pricing source fails or misses cut-off.', impact: ['Hold mint and route to stale-data handling.'], addedWarnings: ['Do not mint on stale NAV.'], addedControls: ['ctl-nav-governance'], addedArtifacts: ['Stale NAV escalation'] },
      { id: 'registry-mismatch', label: 'Registry mismatch', trigger: 'On-chain and administrator books diverge.', impact: ['Freeze transfer and escalate reconciliation.'], addedWarnings: ['Source-of-truth exception active.'], addedControls: ['ctl-reconciliation', 'ctl-incident-response'], addedArtifacts: ['Mismatch report'] },
      { id: 'aml-post-capture', label: 'AML issue after order capture', trigger: 'Post-order compliance review raises a flag.', impact: ['Hold allocation pending review.'], addedWarnings: ['Subscription cannot settle yet.'], addedControls: ['ctl-travel-rule'], addedArtifacts: ['AML exception'] },
      { id: 'redemption-gate', label: 'Redemption gate or suspension', trigger: 'Fund servicing requires gated redemptions.', impact: ['Switch user to gated-servicing view and disclosures.'], addedWarnings: ['Liquidity expectations change materially.'], addedControls: ['ctl-suitability', 'ctl-nav-governance'], addedArtifacts: ['Redemption gate notice'] },
    ],
  },
  {
    id: 'tokenized-bond-issuance',
    title: 'Tokenized bond issuance, distribution, settlement, and servicing',
    summary: 'Mandate to maturity with legal wrapper, issuance, DvP, servicing, and transfer restriction logic.',
    assetFamily: 'Tokenized bond',
    clientSegments: ['institutional', 'issuer'],
    jurisdictions: ['uk', 'ch', 'eu', 'sg'],
    actors: ['Issuer', 'Origination', 'Legal', 'Venue', 'Investors', 'Custodian', 'Paying agent'],
    variables: [
      { id: 'issuanceVenue', label: 'Issuance venue', options: ['DLT venue', 'Permissioned stack', 'Bilateral issuance'], defaultValue: 'DLT venue' },
      { id: 'settlementAsset', label: 'Settlement asset', options: ['Cash leg', 'Tokenized cash'], defaultValue: 'Cash leg' },
    ],
    happyPath: ['Mandate', 'Perimeter', 'Documentation', 'Allocation', 'DvP', 'Servicing', 'Maturity'],
    operationalArtifacts: ['Issuance workflow', 'Open questions register', 'Corporate action map', 'JSON state snapshot'],
    sourceIds: ['boe-dss', 'sdx-official', 'ubs-tokenize'],
    steps: standardStepSet([
      ['mandate', 'Frame mandate, target investors, and wrapper', 'Origination', ['Mandate note'], ['ctl-legal-perimeter']],
      ['perimeter', 'Assess perimeter and documentation design', 'Legal', ['Perimeter memo'], ['ctl-legal-perimeter']],
      ['documentation', 'Prepare identifier, terms, and offering documents', 'Legal', ['Documentation set'], ['ctl-legal-perimeter']],
      ['allocation', 'Collect orders and allocate holdings', 'Distribution', ['Allocation file'], ['ctl-investor-eligibility']],
      ['dvp', 'Settle issuance with DvP controls', 'Settlement', ['Settlement confirmation'], ['ctl-liquidity-prefunding', 'ctl-reconciliation']],
      ['servicing', 'Service coupons and corporate actions', 'Servicing', ['Corporate action calendar'], ['ctl-reconciliation']],
      ['maturity', 'Redeem or restructure at maturity', 'Paying agent', ['Maturity notice'], ['ctl-incident-response']],
    ]),
    branches: [
      { id: 'docs-mismatch', label: 'Documentation misaligned to token mechanics', trigger: 'Terms fail to reflect transfer or servicing design.', impact: ['Route back to legal and pause issuance.'], addedWarnings: ['Do not proceed to investor allocation.'], addedControls: ['ctl-legal-perimeter'], addedArtifacts: ['Documentation mismatch note'] },
      { id: 'investor-ineligible', label: 'Investor distribution restriction issue', trigger: 'Investor type or geography is outside permitted scope.', impact: ['Restrict allocation and update target list.'], addedWarnings: ['Allocation list changed.'], addedControls: ['ctl-investor-eligibility'], addedArtifacts: ['Restriction memo'] },
      { id: 'cash-leg-delay', label: 'Cash leg delayed', trigger: 'DvP is not atomic and cash arrives late.', impact: ['Switch to settlement-failure handling.'], addedWarnings: ['Principal risk window opened.'], addedControls: ['ctl-liquidity-prefunding'], addedArtifacts: ['Settlement exception'] },
      { id: 'coupon-failure', label: 'Coupon servicing failure', trigger: 'Record date or payment process breaks.', impact: ['Escalate servicing and investor communications.'], addedWarnings: ['Corporate action servicing branch active.'], addedControls: ['ctl-incident-response', 'ctl-reconciliation'], addedArtifacts: ['Servicing incident log'] },
      { id: 'cross-border-holding', label: 'Cross-border custody conflict', trigger: 'Holding chain or sub-custody model creates legal uncertainty.', impact: ['Flag legal review and restrict transfer assumptions.'], addedWarnings: ['Cross-border legal review required.'], addedControls: ['ctl-custody-segregation', 'ctl-outsourcing'], addedArtifacts: ['Cross-border custody note'] },
    ],
  },
  {
    id: 'repo-collateral-mobilization',
    title: 'Repo and collateral mobilization with digital assets',
    summary: 'Eligibility, valuation, pledge or transfer, margining, substitution, and unwind with digital assets or tokenized securities.',
    assetFamily: 'Repo and collateral',
    clientSegments: ['institutional', 'corporate-treasury'],
    jurisdictions: ['ch', 'eu', 'sg'],
    actors: ['Borrower', 'Lender', 'Treasury', 'Operations', 'Risk', 'Custodian'],
    variables: [
      { id: 'counterpartyModel', label: 'Counterparty model', options: ['Bilateral', 'Triparty'], defaultValue: 'Triparty' },
      { id: 'valueSensitivity', label: 'Value sensitivity', options: ['medium', 'high'], defaultValue: 'high' },
    ],
    happyPath: ['Eligibility', 'Documentation', 'Selection', 'Transfer', 'Margining', 'Substitution', 'Unwind'],
    operationalArtifacts: ['Collateral checklist', 'Default waterfall', 'Liquidity note', 'JSON state snapshot'],
    sourceIds: ['sdx-official', 'basel-crypto'],
    steps: standardStepSet([
      ['eligibility', 'Confirm eligible collateral and concentration policy', 'Risk', ['Eligibility matrix'], ['ctl-concentration']],
      ['documentation', 'Set repo or collateral terms and limits', 'Legal', ['Repo terms'], ['ctl-legal-perimeter']],
      ['selection', 'Select assets and set haircuts', 'Treasury', ['Collateral selection'], ['ctl-liquidity-prefunding']],
      ['transfer', 'Transfer or lock collateral and settle cash leg', 'Operations', ['Transfer proof'], ['ctl-custody-segregation', 'ctl-reconciliation']],
      ['margining', 'Monitor margin and intraday movements', 'Risk', ['Margin report'], ['ctl-liquidity-prefunding']],
      ['substitution', 'Process substitution or concentration relief', 'Treasury', ['Substitution request'], ['ctl-concentration']],
      ['unwind', 'Unwind, roll, or default-manage', 'Operations', ['Unwind ticket'], ['ctl-incident-response']],
    ]),
    branches: [
      { id: 'stale-valuation', label: 'Collateral valuation stale', trigger: 'Pricing source is stale or disputed.', impact: ['Pause substitution and margin decisions.'], addedWarnings: ['Collateral cannot be relied on at current haircut.'], addedControls: ['ctl-liquidity-prefunding'], addedArtifacts: ['Valuation exception'] },
      { id: 'margin-shortfall', label: 'Margin shortfall', trigger: 'Counterparty fails to meet margin call.', impact: ['Escalate default handling branch.'], addedWarnings: ['Counterparty stress event.'], addedControls: ['ctl-incident-response'], addedArtifacts: ['Shortfall notice'] },
      { id: 'network-outage', label: 'Network outage during unwind', trigger: 'Collateral movement rail is unavailable.', impact: ['Apply failover and liquidity contingency.'], addedWarnings: ['Unwind timing no longer reliable.'], addedControls: ['ctl-liquidity-prefunding', 'ctl-concentration'], addedArtifacts: ['Failover runbook excerpt'] },
      { id: 'legal-uncertainty', label: 'Enforceability uncertainty', trigger: 'Jurisdiction or wrapper changes enforceability confidence.', impact: ['Route to legal-review gate.'], addedWarnings: ['Do not rely on the pattern as executable without specialist review.'], addedControls: ['ctl-legal-perimeter'], addedArtifacts: ['Enforceability note'] },
      { id: 'custody-delegation', label: 'Delegated sub-custody risk', trigger: 'Collateral chain includes sub-custodians or outsourcing.', impact: ['Increase oversight and concentration warnings.'], addedWarnings: ['Sub-custodian path active.'], addedControls: ['ctl-outsourcing', 'ctl-custody-segregation'], addedArtifacts: ['Delegation map'] },
    ],
  },
  {
    id: 'tokenized-cash-payments',
    title: 'Tokenized cash, stablecoin, and tokenized deposit treasury flows',
    summary: 'Treasury and cross-border payments using different tokenized cash models and rail assumptions.',
    assetFamily: 'Tokenized cash',
    clientSegments: ['institutional', 'corporate-treasury'],
    jurisdictions: ['sg', 'hk', 'eu', 'us'],
    actors: ['Treasury', 'Bank rail', 'Compliance', 'Counterparty', 'Operations', 'Accounting'],
    variables: [
      { id: 'cashType', label: 'Tokenized cash type', options: ['Stablecoin', 'Tokenized deposit', 'Bank rail balance'], defaultValue: 'Tokenized deposit' },
      { id: 'crossBorder', label: 'Flow type', options: ['Domestic', 'Cross-border'], defaultValue: 'Cross-border' },
      { id: 'latencyNeed', label: 'Latency need', options: ['medium', 'high'], defaultValue: 'high' },
    ],
    happyPath: ['Use case', 'Perimeter', 'Funding', 'Screening', 'Settlement', 'Reconciliation', 'Monitoring'],
    operationalArtifacts: ['Settlement asset matrix', 'Treasury memo', 'Risk vs reward quadrant', 'JSON state snapshot'],
    sourceIds: ['mas-stablecoin', 'hkma-stablecoin', 'kinexys-digital-payments'],
    steps: standardStepSet([
      ['use-case', 'Define treasury or settlement use case', 'Treasury', ['Use-case note'], ['ctl-liquidity-prefunding']],
      ['perimeter', 'Assess permissible asset and rail', 'Legal / Compliance', ['Perimeter decision'], ['ctl-legal-perimeter']],
      ['funding', 'Fund wallets or accounts and set limits', 'Treasury', ['Funding plan'], ['ctl-liquidity-prefunding']],
      ['screening', 'Run screening and whitelisting checks', 'Compliance', ['Screening result'], ['ctl-travel-rule']],
      ['settlement', 'Execute settlement and monitor confirmation', 'Operations', ['Settlement confirmation'], ['ctl-reconciliation']],
      ['reconcile', 'Reconcile accounting and ledger treatment', 'Accounting', ['Accounting note'], ['ctl-reconciliation']],
      ['monitor', 'Monitor concentration, redemption, and resilience', 'Risk', ['Monitoring pack'], ['ctl-concentration', 'ctl-incident-response']],
    ]),
    branches: [
      { id: 'asset-not-permitted', label: 'Settlement asset not permitted', trigger: 'Chosen tokenized cash type is outside scope for the selected use case.', impact: ['Block the flow and suggest alternate asset types.'], addedWarnings: ['Selected settlement asset blocked.'], addedControls: ['ctl-legal-perimeter'], addedArtifacts: ['Alternative settlement note'] },
      { id: 'receiver-not-whitelisted', label: 'Receiver not whitelisted', trigger: 'Counterparty wallet or account is not eligible.', impact: ['Pause transfer until access is resolved.'], addedWarnings: ['No straight-through settlement.'], addedControls: ['ctl-travel-rule'], addedArtifacts: ['Counterparty access exception'] },
      { id: 'liquidity-gap', label: 'Liquidity not prefunded', trigger: 'Funding model cannot support target timing.', impact: ['Move to treasury funding branch.'], addedWarnings: ['Timing and economics degrade.'], addedControls: ['ctl-liquidity-prefunding'], addedArtifacts: ['Prefunding shortfall note'] },
      { id: 'finality-delay', label: 'Settlement finality delay', trigger: 'Rail or network confirmation is slower than assumed.', impact: ['Extend reconciliation and limit monitoring.'], addedWarnings: ['Intraday exposure remains open.'], addedControls: ['ctl-liquidity-prefunding', 'ctl-reconciliation'], addedArtifacts: ['Finality delay note'] },
      { id: 'issuer-risk-spike', label: 'Issuer or vendor risk spike', trigger: 'Stablecoin or rail concentration risk becomes material.', impact: ['Increase oversight and compare alternative models.'], addedWarnings: ['Concentration tolerance breached.'], addedControls: ['ctl-concentration'], addedArtifacts: ['Dependency escalation'] },
    ],
  },
  {
    id: 'structured-product-lifecycle',
    title: 'Structured product lifecycle',
    summary: 'Idea framing, payoff design, distribution fit, issuance, servicing, and unwind for digital-asset-linked or tokenized structures.',
    assetFamily: 'Structured product',
    clientSegments: ['affluent', 'hnw', 'uhnw', 'family-office', 'institutional'],
    jurisdictions: ['uk', 'sg', 'eu', 'us'],
    actors: ['Product', 'Sales', 'Legal', 'Risk', 'Hedging desk', 'Operations', 'Client'],
    variables: [
      { id: 'targetSegment', label: 'Target segment', options: ['affluent', 'hnw', 'uhnw', 'family-office', 'institutional'], defaultValue: 'hnw' },
      { id: 'payoffType', label: 'Payoff type', options: ['Capital protected', 'Yield-enhanced', 'Barrier linked'], defaultValue: 'Yield-enhanced' },
    ],
    happyPath: ['Problem framing', 'Payoff design', 'Target market', 'Documentation', 'Issuance', 'Servicing', 'Maturity'],
    operationalArtifacts: ['Concept note', 'Target-market warnings', 'Open questions register', 'JSON state snapshot'],
    sourceIds: ['ubs-tokenize', 'fca-future-crypto', 'sec-crypto-2026'],
    steps: standardStepSet([
      ['problem', 'Frame client problem and objective', 'Product', ['Problem statement'], ['ctl-suitability']],
      ['design', 'Design payoff and wrapper', 'Product', ['Payoff sheet'], ['ctl-legal-perimeter']],
      ['target-market', 'Assess target segment and disclosures', 'Sales / Compliance', ['Target market note'], ['ctl-suitability']],
      ['documentation', 'Prepare terms, hedging, and issuance pack', 'Legal / Risk', ['Termsheet'], ['ctl-legal-perimeter']],
      ['issuance', 'Issue and distribute product', 'Operations', ['Issuance record'], ['ctl-reconciliation']],
      ['servicing', 'Monitor barriers, valuation, and events', 'Operations', ['Servicing log'], ['ctl-incident-response']],
      ['maturity', 'Unwind or mature the structure', 'Operations', ['Maturity summary'], ['ctl-reconciliation']],
    ]),
    branches: [
      { id: 'too-complex', label: 'Payoff too complex for target segment', trigger: 'Complexity exceeds target-market tolerance.', impact: ['Switch to challenge view and simplify the structure.'], addedWarnings: ['Target-market fit failed.'], addedControls: ['ctl-suitability'], addedArtifacts: ['Target-market challenge note'] },
      { id: 'hedging-weak', label: 'Hedging or liquidity weak', trigger: 'The structure depends on fragile hedging assumptions.', impact: ['Reduce viability score and pause launch.'], addedWarnings: ['Economic and risk case weakened.'], addedControls: ['ctl-liquidity-prefunding'], addedArtifacts: ['Hedging concern note'] },
      { id: 'wrapper-conflict', label: 'Legal wrapper conflict', trigger: 'Wrapper assumptions do not hold across the selected markets.', impact: ['Route to market-comparison branch.'], addedWarnings: ['Cross-border legal review required.'], addedControls: ['ctl-legal-perimeter'], addedArtifacts: ['Wrapper conflict note'] },
      { id: 'valuation-dispute', label: 'Valuation dispute', trigger: 'Valuation source or barrier event treatment is disputed.', impact: ['Escalate servicing and client communication.'], addedWarnings: ['Servicing confidence reduced.'], addedControls: ['ctl-incident-response'], addedArtifacts: ['Valuation dispute memo'] },
      { id: 'family-governance', label: 'Family governance overlay', trigger: 'UHNW or family-office wrapper is selected.', impact: ['Add authority, succession, and concentration questions.'], addedWarnings: ['Private-client governance review required.'], addedControls: ['ctl-wealth-governance'], addedArtifacts: ['Family governance checklist'] },
    ],
  },
];

export const releaseNotes: ReleaseNote[] = [
  {
    id: '2026-03-19-foundation',
    title: 'Foundation release',
    releasedAt: '2026-03-19',
    summary: 'Initial release candidate covering the static shell, typed content model, rules, six deep simulations, workspace, strategy workbench, and business model simulator.',
    highlights: ['GitLab Pages-safe Astro build', 'Source-backed markets and controls', 'Interactive workbench and simulator'],
  },
  {
    id: '2026-03-19-governance',
    title: 'Governance and trust improvements',
    releasedAt: '2026-03-19',
    summary: 'Added stale-state visibility, release history, workspace migrations, and CI verification gates.',
    highlights: ['Staleness checks', 'Release notes route', 'Migration-aware workspace import'],
  },
];

export const contentPackVersions: ContentPackVersion[] = [
  {
    id: 'core-catalog',
    version: '1.0.0',
    releasedAt: '2026-03-19',
    changes: ['Initial knowledge graph', 'Initial control library', 'Initial six simulations'],
    backwardCompatible: true,
  },
  {
    id: 'workspace-schema',
    version: '2.0.0',
    releasedAt: '2026-03-19',
    changes: ['Added workbench projects', 'Added business model scenarios', 'Added migration handling from schemaVersion 1'],
    backwardCompatible: true,
  },
];
